# docker-compose.yml
version: '3.8'

services:
  db:
    image: postgres:15
    container_name: talkabout_db
    environment:
      - POSTGRES_USER=talkabout_user
      - POSTGRES_PASSWORD=talkabout_password
      - POSTGRES_DB=talkabout_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  redis:
    image: redis:7-alpine
    container_name: talkabout_redis
    ports:
      - "6379:6379"
volumes:
  postgres_data: